POST http://localhost:3003/api/users 
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "hell12%%"
}

###
POST http://localhost:3003/api/users 
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "matLukK9#45"
}